### ISSUE TITLE
filter allows incompatible options

### ISSUE THREAD

**Issue by ZXGuesser** [ali1234/vhs-teletext#29]
running filter with a non zero `-r` prevents it from matching any pages/subpages to `-p` and `-s`

**Comment by ali1234** [comment]
This happens because the row filtering is applied before pagination/page filtering. If row filtering removes headers, then the stream can't be paginated.

There is one small problem with this: the packet stream is filtered by a decorator before it even reaches the part of the code that needs headers. So the header-using code can't tell if rows have been filtered or not.

The easiest way around this is to add an extra argument: just a bool that indicates if headers have been filtered or not.
